# Generated by Django 4.2 on 2024-08-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdimage',
            name='code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='vdimage',
            name='image',
            field=models.ImageField(upload_to='detect_vehicles/yolov5s/'),
        ),
    ]
