# Generated by Django 4.2 on 2024-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc_backend_app', '0003_vdimage_model_alter_vdimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdimage',
            name='gen_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vdimage',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='vdimage',
            name='model',
            field=models.TextField(choices=[('YOLOv5s', 'YOLOV5S'), ('R-CNN', 'RCNN')], default='YOLOv5s'),
        ),
    ]
