# Generated by Django 4.2 on 2024-08-04 09:14

from django.db import migrations, models
import vc_backend_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('vc_backend_app', '0005_rename_gen_time_vdimage_inf_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('image', models.ImageField(upload_to=vc_backend_app.models.get_image_upload_path)),
                ('inf_time', models.FloatField(default=0.0)),
                ('model', models.TextField(choices=[('EfficientNetB1', 'EFFNETB1'), ('X', 'X')], default='EfficientNetB1')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
