# Generated by Django 4.2 on 2024-08-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc_backend_app', '0006_vcimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcimage',
            name='pred_class',
            field=models.TextField(default='None'),
        ),
    ]
