# Generated by Django 4.2 on 2024-08-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc_backend_app', '0007_vcimage_pred_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdimage',
            name='model',
            field=models.TextField(choices=[('YOLOv5s', 'YOLOV5S'), ('YOLOv8s', 'YOLOV8S')], default='YOLOv5s'),
        ),
    ]
