# Generated by Django 5.1 on 2024-08-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc_backend_app', '0008_alter_vdimage_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcimage',
            name='model',
            field=models.TextField(choices=[('EfficientNetB1', 'EFFNETB1'), ('YOLOv8s-cls', 'YOLOV8SCLS')], default='EfficientNetB1'),
        ),
    ]
