<template>
    <div class="terms-of-service">
      <div class="header">
        <h1>Terms of Service</h1>
        <p class="update-info">Updated: September 22, 2024</p>
        <br />
      </div>
  
      <div class="text">
        <p>Hello there! Thank you for using our app.</p>
        <br />
        <p>
          These Terms of Service govern your use of the Vehicle Detection and Classification app
          (referred to as the Perseids). By accessing or using the Perseids, you agree to these Terms.
          If you do not agree, please do not use the Perseids.
        </p>
  
        <h2>Usage of the Perseids</h2>
        <br />
        <p>
          You may use the Perseids only for its intended purposes: detecting and classifying vehicles
          through uploaded images. By using the Perseids, you must comply with all applicable laws
          and regulations and ensure that the content you provide does not infringe the rights of others.
        </p>
  
        <h3>You agree not to:</h3>
        <ul>
          <li>Use the Perseids for illegal or harmful purposes.</li>
          <li>Reverse engineer, decompile, or attempt to discover the source code of the Perseids.</li>
          <li>Upload any harmful content, including viruses or other malicious software.</li>
          <li>Access the Perseids using automated means without our permission.</li>
          <li>Use the Perseids in a way that could interfere with the Perseids’s normal operation or disrupt services to other users.</li>
        </ul>
  
        <p>
          We may suspend or terminate your access to the Perseids if we determine that you have violated these Terms.
        </p>
  
        <h2>Responsibilities and Rights of the User</h2>
        <br />
        <p>As a user of the Perseids, you are responsible for:</p>
        <ul>
          <li>Providing accurate and lawful content.</li>
          <li>Using the Perseids in a manner that respects the rights of others and complies with applicable laws.</li>
          <li>Ensuring that any vehicle-related data you submit is yours or that you have the necessary rights to submit it.</li>
        </ul>
  
        <p>You have the right to:</p>
        <ul>
          <li>Use the Perseids to detect and classify vehicles based on your uploaded content.</li>
          <li>Receive results generated by the Perseids from your content.</li>
          <li>Contact us for support or questions regarding the Perseids.</li>
        </ul>
  
        <p>
          However, we reserve the right to terminate or limit your access if your usage violates these Terms or infringes on the rights of others.
        </p>
  
        <h2>Intellectual Property</h2>
        <br />
        <p>
          The Perseids, including all content, designs, logos, and software, is the intellectual property of the company that operates the Perseids, and all rights are reserved. You may not use, copy, modify, distribute, or reverse engineer any part of the Perseids unless expressly authorized.
        </p>
        <p>
          Any data or images you upload for the purposes of vehicle detection and classification remain your property, and you grant us a non-exclusive, worldwide, royalty-free license to use, display, and process this content for the purpose of operating and improving the Perseids.
        </p>
  
        <h2>Disclaimer Policy</h2>
        <br />
        <p>
          The Perseids is provided "as is" without warranties of any kind. We make no guarantees regarding the accuracy or reliability of the vehicle detection or classification results provided by the Perseids. Use of the Perseids is at your own risk, and we disclaim all warranties, whether express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement.
        </p>
        <p>
          We are not responsible for any errors, delays, or interruptions in the Perseids's service. The vehicle classifications and detections made by the Perseids may not always be accurate and should not be relied upon for critical decision-making.
        </p>
  
        <h2>Contact Information</h2>
        <br />
        <p>
          If you have any questions or concerns about these Terms or the Perseids, you can contact us at:
        </p>
        <p style="color: #02af98">
            carvarsou@alum.us.es
        </p>
  
        <p>
          By using the Perseids, you agree to these Terms and acknowledge that they may be updated from time to time.
        </p>
      </div>
      <p v-for="n in 5" :key="n"><br /></p>
    </div>
  </template>
  
  <style scoped>

  .terms-of-service {
    color: #083863;
    text-align: justify;
    padding: 20px;
    width: 200%;
  }
  
  .header h1 {
    font-size: 2.8rem;
    margin-top: 6.5rem;
    font-weight: 500;
    text-align: center;
  }
  
  .update-info {
    font-size: 1rem;
    color: #6b7280;
    text-align: center;
  }
  
  .text h2 {
    font-size: 1.8rem;
    margin-top: 20px;
    font-weight: 500;
  }
  
  .text h3 {
    font-size: 1.3rem;
    margin-top: 15px;
  }
  
  .text p {
    font-size: 1.3rem;
    margin-bottom: 1em;
    line-height: 1.6;
  }
  
  ul {
    list-style-type: disc;
    margin-left: 20px;
  }
  
  ul li {
    font-size: 1.3rem;
    margin-bottom: 0.5em;
  }
  </style>
  